trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  nodeVersion: '14.x'
  webAppName: '$(webappname)'
  environmentName: '$(envname)'
  azureResourceGroup: '$(resourcegroupname)'
  azureAppServicePlan: '$(appserviceplanname)'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(nodeVersion)
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build --if-present
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- upload: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
  displayName: 'Upload package'
  artifact: drop

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: '$(azureSubscription)'
    appType: 'webApp'
    WebAppName: $(webAppName)
    packageForLinux: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
    deploymentMethod: 'auto'
  displayName: 'Deploy to Azure Web App'